version: 2
jobs:
  build:
    machine: true
    working_directory: ~/code
    steps:
      - checkout:
          path: ~/code
      - run:
          name: setup
          command: 'sudo apt-get update; sudo apt-get install gcc-4.9; sudo apt-get upgrade libstdc++6; sudo apt-get dist-upgrade; strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX'
      - run:
          name: validate setup
          command: 'strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX'
      - run:
          name: build
          command: 'cd ~/code; chmod 775 gradlew; ./gradlew assemble'
      - run:
          name: deploy
          command: 'sls deploy' # todo install sls
