version: 2
jobs:
  build:
    machine: true
    working_directory: ~/code
    steps:
      - checkout:
          path: ~/code
      - run:
          name: build
          command: 'cd ~/code; chmod 775 gradlew; ./gradlew assemble'
      - run:
          name: deploy
          command: 'sls deploy' # todo install sls
